# -*- coding: utf-8 -*-
{
	'name': 'Auction Website',
	'version': '1',
	'author': 'Atlas',
	'depends': ['base',
				'base_import',
				'payment',
				'product',
				'sale',
				'sale_management',
				'stock',
				'website',
				'website_sale',
				'auction_status',
				'auth_signup'],
	'data': ['views/auction_views.xml',
			 'views/auth_signup.xml',
			 'views/bid_views.xml',
			 'views/product_template_views.xml',
			 'views/home.xml',
			 'views/auctions.xml',
			 'views/lots.xml',
			 'views/lot.xml',
			 'views/assets.xml',
			 'views/past_auctions.xml',
			 'views/res_partner_views.xml',
			 'views/res_config_settings.xml',
			'views/portal_templates.xml',
			 'views/website_search_box.xml',
			 'security/ir.model.access.csv',
			 'data/website_page.xml',
			 'data/email_template.xml',
			 'data/auction_menus.xml',
			 'data/ir_cron.xml'],
	'qweb': ['views/base_import.xml', 'static/src/xml/searchbar_autocomplete.xml'],
	'installable': True,
	'application': True,
	'auto_install': False,
}