# -*- coding: utf-8 -*-
{
    'name': 'HR customization addon',
    'version': '13.0.3.1',
    'category': 'Uncategorized',
    'description': """
Module that contains HR module customization for Odoo
""",
    'author': "AgileVision.io(developed for Nanoramic)",
    'website': "https://agilevision.io",
    'depends': [
        'base',
        'web',
        'hr',
        'hr_contract_reports',
        'hr_contract',
        'hr_maintenance',
        'mail',
        'contacts',
        'timesheet_grid',
        'calendar',
        'documents',
        'documents_hr',
        'hr_skills',
        'hr_holidays',
        'addon_holidays',
        'addon_hide_send_email_button',
        'addon_google_integration',
        'addon_restful',
        'addon_editor_js',
        'addon_email_config',
        'addon_custom_breadcrumbs',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/hr_data.xml',
        'data/hr_languages_data.xml',
        'data/hr_tshirt_size_data.xml',
        'data/hr_cron.xml',
        'data/mail_template.xml',
        'data/slack_defaults.xml',
        'views/hr_employee_flag_views.xml',
        'views/res_partner_inherit_view.xml',
        'views/hr_views.xml',
        'views/responsibility_assign_asset.xml',
        'views/email_templates/assignment.xml',
        'views/hr_timesheet_views.xml',
        'views/hr_employee_views.xml',
        'views/calendar_views.xml',
        'views/hr_employee_work_location_view.xml',
        'views/res_config_view.xml',
        'views/holiday.xml',
        'views/hr_language.xml',
        'views/hr_employee_kanban_color_views.xml',
        'views/hr_employee_education_level_views.xml',
        'views/hr_employee_locations_views.xml',
        'views/hr_employee_documents_views.xml',
        'views/hr_employee_relationships_views.xml',
        'views/hr_employee_health_documents_views.xml',
        'views/hr_employee_citizenship_document.xml',
        'views/hr_employee_travel_document.xml',
        'views/hr_employee_alert_views.xml',
        'views/hr_employee_faq.xml',
        'views/corporate_value_views.xml',
        'data/hr_employee_relationships_data.xml',
        'data/hr_employee_education_level_data.xml',
        'data/hr_documents_data.xml',
        'wizard/event_create_timesheet.xml',
        'wizard/create_employee.xml',
        'wizard/activate_employee.xml',
        'wizard/force_employee_transition.xml',
        'views/hr_employee_activities.xml',
        'views/hr_employee_dietary_restriction_views.xml',
        'views/hr_loyalty_program_views.xml',
        'views/ir_ui_menu_views.xml',
        'data/hr_employee_dietary_restriction_data.xml',
        'data/hr_loyalty_program_data.xml',
        'data/travel_special_assistance_data.xml',
        'views/employment_period_views.xml',
    ],
    'qweb': [
        'static/src/xml/calendar.xml',
    ],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False
}
